# Generated by Django 5.2.2 on 2025-06-05 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
                ("telefono", models.CharField(max_length=10)),
                ("correo", models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vin", models.CharField(max_length=17)),
                ("marca", models.CharField(max_length=20)),
                ("modelo", models.CharField(max_length=20)),
                ("año", models.IntegerField()),
                ("placa", models.CharField(max_length=7)),
                ("servicio", models.CharField(max_length=200)),
                ("comentario", models.CharField(max_length=200)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autocheckxapi.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inspeccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marca",
                    models.CharField(
                        choices=[
                            ("nissan", "Nissan"),
                            ("hyundai", "Hyundai"),
                            ("mazda", "Mazda"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_servicio", models.DateField()),
                (
                    "luces_frontales",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "luces_posteriores",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("carga_bateria", models.IntegerField(blank=True, null=True)),
                ("presion_llanta_uno", models.FloatField(blank=True, null=True)),
                ("presion_llanta_dos", models.FloatField(blank=True, null=True)),
                ("presion_llanta_tres", models.FloatField(blank=True, null=True)),
                ("presion_llanta_cuatro", models.FloatField(blank=True, null=True)),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autocheckxapi.vehiculo",
                    ),
                ),
            ],
        ),
    ]
