# Generated by Django 5.2.2 on 2025-06-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autocheckxapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiculo",
            name="fecha_registro",
            field=models.DateField(blank=True, null=True),
        ),
    ]
