# Generated by Django 5.2.2 on 2025-06-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autocheckxapi", "0002_vehiculo_fecha_registro"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="apellido_materno",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="cliente",
            name="apellido_paterno",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
