# Generated by Django 5.2.2 on 2025-06-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autocheckxapi", "0003_cliente_apellido_materno_cliente_apellido_paterno"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspeccion",
            name="estatus",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
