# Generated by Django 5.2.2 on 2025-06-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autocheckxapi", "0004_inspeccion_estatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspeccion",
            name="marca",
            field=models.CharField(max_length=20),
        ),
    ]
