# Generated by Django 5.2.2 on 2025-06-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autocheckxapi", "0005_alter_inspeccion_marca"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiculo",
            name="comentario",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
