# Generated by Django 5.2.2 on 2025-06-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autocheckxapi", "0006_alter_vehiculo_comentario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspeccion",
            name="fecha_servicio",
            field=models.DateField(blank=True),
        ),
    ]
