# Generated by Django 5.2.2 on 2025-06-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autocheckxapi", "0007_alter_inspeccion_fecha_servicio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspeccion",
            name="fecha_servicio",
            field=models.DateField(blank=True, null=True),
        ),
    ]
